<a href="https://colab.research.google.com/github/devrajsengar786-sssup/Devraj-singh-sengar/blob/main/Data_analytics_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY LAB ASSIGNMENT
1. Aim of the Experiment

To perform numerical computations, matrix operations, and statistical analysis using NumPy and apply them to real-world datasets such as student marks and sales data.


**#Case Study 1: Student Marks Analysis**

 Problem Statement:

Analyze student performance using NumPy.


In [1]:
# Step 1: Import Library
import numpy as np

In [2]:
# Step 2: Dataset
marks = np.array([
    [80, 75, 90],
    [60, 88, 70],
    [95, 92, 85],
    [70, 65, 60],
    [88, 78, 84]
])

print("Marks Dataset:\n", marks)

Marks Dataset:
 [[80 75 90]
 [60 88 70]
 [95 92 85]
 [70 65 60]
 [88 78 84]]


In [3]:
# Task 1: Total Marks of Each Student
total_marks = np.sum(marks, axis=1)
print("Total Marks:", total_marks)

Total Marks: [245 218 272 195 250]


In [4]:
# Task 2: Average Marks Per Student
average_marks = np.mean(marks, axis=1)
print("Average Marks:", average_marks)

Average Marks: [81.66666667 72.66666667 90.66666667 65.         83.33333333]


In [5]:
# Task 3: Identify Topper
topper_index = np.argmax(total_marks)
print("Topper is Student", topper_index + 1)

Topper is Student 3


In [6]:
# Task 4: Subject-wise Highest Score
subject_highest = np.max(marks, axis=0)
print("Highest Score in Each Subject:", subject_highest)

Highest Score in Each Subject: [95 92 90]


In [7]:
# Task 5: Standard Deviation of Each Subject
subject_std = np.std(marks, axis=0)
print("Standard Deviation of Each Subject:", subject_std)

Standard Deviation of Each Subject: [12.48358923  9.60416576 11.1067547 ]


**#Interpretation (Student Performance)**

1.Student 3 has the highest total marks, so they are the topper.

2.Subject-wise highest marks show Subject 1 and 2 have very high performers.

3.Standard deviation indicates moderate variation among students.

4.Students with consistent averages show balanced performance across subjects.


**#Case Study 3: Sales Analysis**

Problem Statement:

Analyze weekly sales performance.

In [8]:
# Dataset
sales = np.array([1200, 1500, 1100, 1700, 1600, 1800, 1400])
print("Sales Data:", sales)


Sales Data: [1200 1500 1100 1700 1600 1800 1400]


In [9]:
# Task 1: Average Daily Sales
average_sales = np.mean(sales)
print("Average Daily Sales:", average_sales)

Average Daily Sales: 1471.4285714285713


In [10]:
# Task 2: Day with Highest Sales
highest_day = np.argmax(sales)
print("Highest Sales on Day", highest_day + 1)

Highest Sales on Day 6


In [11]:
# Task 3: Percentage Growth (Day 1 to Day 7)
growth = ((sales[-1] - sales[0]) / sales[0]) * 100
print("Percentage Growth:", growth, "%")

Percentage Growth: 16.666666666666664 %


In [12]:
# Task 4: Cumulative Sales
cumulative_sales = np.cumsum(sales)
print("Cumulative Sales:", cumulative_sales)

Cumulative Sales: [ 1200  2700  3800  5500  7100  8900 10300]


In [13]:
# Task 5: Standard Deviation
sales_std = np.std(sales)
print("Standard Deviation:", sales_std)

Standard Deviation: 237.33211036908787


**#Interpretation (Sales Pattern)**

1.The average daily sales give an overall business performance measure.

2.The highest sales occurred on Day 6, showing peak customer activity.

3.There is a positive growth from Day 1 to Day 7, indicating improvement.

4.Standard deviation shows moderate fluctuation in daily sales.

5.Cumulative sales show steady revenue growth across the week.

****#Conclusion****

🔹 Insights Derived

1.NumPy makes large numerical computations simple and efficient.

2.Vectorized operations are faster than manual loops.

3.Statistical measures help in identifying trends and performance gaps.

4.Real-world datasets can be easily analyzed using NumPy functions.


🔹 Most Useful NumPy Functions

1.np.sum()

2.np.mean()

3.np.std()

4.np.argmax()

5.np.cumsum()

🔹 Importance in Data Analytics

Numerical computation helps in extracting meaningful insights from raw data. It supports decision-making by identifying trends, variations, and growth patterns efficiently.