<a href="https://colab.research.google.com/github/devrajsengar786-sssup/Devraj-singh-sengar/blob/main/Module2_Activity2_1_NumPy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Course: Data Analytics Using Python (AIL0202)
## Module 2 – Activity 2.1
### NumPy Hands-on Lab (5 Marks)


### Instructions:
- Complete all tasks.
- Run each cell and show outputs.
- Add comments wherever required.
- Submit the completed notebook(PDF) on LMS.

Name:DEVRAJ SINGH SENGAR

Roll No.:BETN1AI25230


In [ ]:
# Import NumPy
import numpy as np
print('NumPy Version:', np.__version__)


## Task 1: Array Creation(1 Mark)

Create:

1D array of 10 integers

2D array (3×3 matrix)

Identity matrix of size 4

Random array (5×5)

In [1]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1D Array:")
print(array_1d)

matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
print("\n3x3 Matrix:")
print(matrix_3x3)

identity_matrix = np.eye(4)
print("\nIdentity Matrix (4x4):")
print(identity_matrix)

random_matrix = np.random.rand(5, 5)
print("\nRandom 5x5 Matrix:")
print(random_matrix)


1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Identity Matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random 5x5 Matrix:
[[0.59960157 0.84085061 0.6603762  0.13230596 0.58853672]
 [0.62173254 0.83063076 0.01001802 0.62403066 0.613568  ]
 [0.60164805 0.9634165  0.5442467  0.96899081 0.80017443]
 [0.45966227 0.99682758 0.09707017 0.94357046 0.86354908]
 [0.1528492  0.2406875  0.90081174 0.87851369 0.3462768 ]]


## Task 2: Indexing & Slicing (1 Mark)

Given:

A = np.arange(1, 26).reshape(5,5)

Perform:

Extract 2nd row

Extract 3rd column

Extract 2×2 submatrix (center)

Reverse last row

In [2]:
import numpy as np

A = np.arange(1, 26).reshape(5,5)
print("Matrix A:")
print(A)

second_row = A[1]
print("\n2nd Row:")
print(second_row)

third_column = A[:, 2]
print("\n3rd Column:")
print(third_column)

center_matrix = A[1:3, 1:3]
print("\n2x2 Center Matrix:")
print(center_matrix)

reversed_last_row = A[-1][::-1]
print("\nReversed Last Row:")
print(reversed_last_row)


Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

2nd Row:
[ 6  7  8  9 10]

3rd Column:
[ 3  8 13 18 23]

2x2 Center Matrix:
[[ 7  8]
 [12 13]]

Reversed Last Row:
[25 24 23 22 21]


## Task 3: Broadcasting(1 Mark)

Perform broadcasting operations on matrix A created in Task-2.

Add scalar 10 to matrix A

Add vector [1,2,3,4,5] to each row

Normalize matrix values between 0–1

In [3]:
import numpy as np

A = np.arange(1, 26).reshape(5,5)
print("Original Matrix A:")
print(A)

add_scalar = A + 10
print("\nAfter Adding Scalar 10:")
print(add_scalar)

vector = np.array([1, 2, 3, 4, 5])
add_vector = A + vector
print("\nAfter Adding Vector [1,2,3,4,5] to each row:")
print(add_vector)

normalized = (A - A.min()) / (A.max() - A.min())
print("\nNormalized Matrix (0–1 range):")
print(normalized)

Original Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

After Adding Scalar 10:
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]

After Adding Vector [1,2,3,4,5] to each row:
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]]

Normalized Matrix (0–1 range):
[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


## Task 4: Vectorized Computation(1 Marks)

Perform element-wise multiplication
Compute dot product
Compute mean, standard deviation

In [ ]:
import numpy as np

X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])

elementwise = X * Y
print("Element-wise Multiplication:")
print(elementwise)

dot_product = np.dot(X, Y)
print("\nDot Product:")
print(dot_product)

mean_X = np.mean(X)
mean_Y = np.mean(Y)
print("\nMean of X:", mean_X)
print("Mean of Y:", mean_Y)

std_X = np.std(X)
std_Y = np.std(Y)
print("\nStandard Deviation of X:", std_X)
print("Standard Deviation of Y:", std_Y)

Task 5: Mini Case Problem (1 Mark)

Dataset: Student marks (5 students, 3 subjects)

Compute total and average per student

Find topper

Find subject-wise highest score

In [4]:
import numpy as np

marks = np.array([
    [80,75,90],
    [60,88,70],
    [95,92,85],
    [70,65,60],
    [88,78,84]
])

print("Marks Matrix:")
print(marks)

total = np.sum(marks, axis=1)
print("\nTotal Marks per Student:")
print(total)

average = np.mean(marks, axis=1)
print("\nAverage Marks per Student:")
print(average)

topper_index = np.argmax(total)
print("\nTopper Student Index (0-based):", topper_index)
print("Topper Total Marks:", total[topper_index])

subject_highest = np.max(marks, axis=0)
print("\nSubject-wise Highest Scores:")
print(subject_highest)

Marks Matrix:
[[80 75 90]
 [60 88 70]
 [95 92 85]
 [70 65 60]
 [88 78 84]]

Total Marks per Student:
[245 218 272 195 250]

Average Marks per Student:
[81.66666667 72.66666667 90.66666667 65.         83.33333333]

Topper Student Index (0-based): 2
Topper Total Marks: 272

Subject-wise Highest Scores:
[95 92 90]
