<a href="https://colab.research.google.com/github/devrajsengar786-sssup/Devraj-singh-sengar/blob/main/Module2_Activity2_1_NumPy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Course: Data Analytics Using Python (AIL0202)
## Module 2 – Activity 2.1
### NumPy Hands-on Lab (5 Marks)


### Instructions:
- Complete all tasks.
- Run each cell and show outputs.
- Add comments wherever required.
- Submit the completed notebook(PDF) on LMS.

Name:DEVRAJ SINGH SENGAR

Roll No.:BETN1AI25230


In [1]:
# Import NumPy
import numpy as np
print('NumPy Version:', np.__version__)


NumPy Version: 2.0.2


## Task 1: Array Creation(1 Mark)

Create:

1D array of 10 integers

2D array (3×3 matrix)

Identity matrix of size 4

Random array (5×5)

In [6]:
# Create required arrays her
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 1D array of 10 integers
print("1D Array:")
print(arr)
# 3x3 matrix
arr2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("\n3x3 Matrix:")
print(arr2)

# Identity matrix of size 4

arr3 = np.eye(4)
print("\nIdentity Matrix (4x4):")
print(arr3)

# Random 5x5 matrix
arr4 = np.random.rand(5, 5)
print("\nRandom 5x5 Matrix:")
print(arr4)


1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Identity Matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random 5x5 Matrix:
[[0.41092004 0.57588153 0.15368827 0.21944324 0.81597741]
 [0.17718545 0.0470068  0.78988761 0.17846592 0.25404844]
 [0.83232597 0.43951555 0.41621816 0.83467237 0.69603219]
 [0.01424657 0.90013149 0.5722961  0.61685004 0.09578446]
 [0.08621703 0.17151613 0.73883316 0.18630761 0.80882786]]


## Task 2: Indexing & Slicing (1 Mark)

Given:

A = np.arange(1, 26).reshape(5,5)

Perform:

Extract 2nd row

Extract 3rd column

Extract 2×2 submatrix (center)

Reverse last row

In [17]:
A = np.arange(1, 26).reshape(5,5)
print("MATRIX A")
print(A)

# Extract 2nd row

row2 = A[1]
print("\n2nd Row:")
print(row2)

# Extract 3rd column

column3 = A[:, 2]
print("\n3rd Column:")
print(column3)

# Extract 2x2 center matrix

center_matrix = A[1:3, 1:3]
print("\n2x2 Center Matrix:")
print(center_matrix)

# Reverse last row
reversed_last_row = A[-1][::-1]
print("\nReversed Last Row:")
print(reversed_last_row)

MATRIX A
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

2nd Row:
[ 6  7  8  9 10]

3rd Column:
[ 3  8 13 18 23]

2x2 Center Matrix:
[[ 7  8]
 [12 13]]

Reversed Last Row:
[25 24 23 22 21]


## Task 3: Broadcasting(1 Mark)

Perform broadcasting operations on matrix A created in Task-2.

Add scalar 10 to matrix A

Add vector [1,2,3,4,5] to each row

Normalize matrix values between 0–1

In [22]:
# Perform broadcasting operations here

a = np.arange(1, 26).reshape(5,5)
print("Original Matrix A:")
print(a)

# Add scalar 10 to matrix

add = a + 10
print("\nAfter Adding Scalar 10:")
print(add)

# Add vector [1,2,3,4,5] to each row

vector = np.array([1, 2, 3, 4, 5])
add_vector = a + vector
print("\nAfter Adding Vector [1,2,3,4,5] to each row:")
print(add_vector)

# Normalize matrix between 0 and 1
normalized = (a - a.min()) / (a.max() - a.min())
print("\nNormalized Matrix (0–1 range):")
print(normalized)

Original Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

After Adding Scalar 10:
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]

After Adding Vector [1,2,3,4,5] to each row:
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]]

Normalized Matrix (0–1 range):
[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


## Task 4: Vectorized Computation(1 Marks)

Perform element-wise multiplication
Compute dot product
Compute mean, standard deviation

In [24]:
X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])

# Element-wise multiplication

multiply = X * Y
print("Element-wise Multiplication:")
print(multiply)

# Dot product
product = np.dot(X, Y)
print("\nDot Product:")
print(product)
# Mean and Standard Deviation

mean_X = np.mean(X)
mean_Y = np.mean(Y)
print("\nMean of X:", mean_X)
print("Mean of Y:", mean_Y)

standard_X= np.std(X)
standard_Y = np.std(Y)
print("\nStandard Deviation of X:", standard_X)
print("Standard Deviation of Y:",standard_Y )

Element-wise Multiplication:
[ 5 12 21 32]

Dot Product:
70

Mean of X: 2.5
Mean of Y: 6.5

Standard Deviation of X: 1.118033988749895
Standard Deviation of Y: 1.118033988749895


Task 5: Mini Case Problem (1 Mark)

Dataset: Student marks (5 students, 3 subjects)

Compute total and average per student

Find topper

Find subject-wise highest score

In [32]:
marks = np.array([[80,75,90],[60,88,70],[95,92,85],[70,65,60],[88,78,84]])
# Compute totals, averages, topper
print("marks matrix")
print(marks)

total= np.sum(marks,axis=1)
print("\ntotal marks")
print(total)

average=np.mean(marks,axis=1)
print("\naverage marks")
print(average)

topper=np.argmax(total)
print("\ntopper student marks",total[topper])


marks matrix
[[80 75 90]
 [60 88 70]
 [95 92 85]
 [70 65 60]
 [88 78 84]]

total marks
[245 218 272 195 250]

average marks
[81.66666667 72.66666667 90.66666667 65.         83.33333333]

topper student marks 272
